//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAuthenticationToken
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_posts_skill_sets
    {
        public int skill_set_id { get; set; }
        public int job_post_id { get; set; }
        public int skill_level { get; set; }
    
        public virtual JobOpening JobOpening { get; set; }
        public virtual tbl_Skill tbl_Skill { get; set; }
    }
}
