//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAuthenticationToken
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTable
    {
        public int pEmployeId { get; set; }
        public string pEmailId { get; set; }
        public string pPhoneNo { get; set; }
        public string pJobName { get; set; }
        public string pLocation { get; set; }
        public string pSkillSet { get; set; }
        public string pName { get; set; }
    }
}
